name: build

on:
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get install -y upx
          wget https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.13.5.linux-amd64.tar.gz
      - name: build
        run: |
          mkdir tmp
          mkdir bin
          git clone https://github.com/v2ray/v2ray-core.git
          sed -i 's/_ "v2ray.com\/core\/main\/json"/\/\/_ "v2ray.com\/core\/main\/json"/' v2ray-core/main/distro/all/all.go
          sed -i 's/\/\/ _ "v2ray.com\/core\/main\/jsonem"/_ "v2ray.com\/core\/main\/jsonem"/' v2ray-core/main/distro/all/all.go
          wget https://raw.githubusercontent.com/felix-fly/v2ray-openwrt/master/build.sh
          chmod +x ./build.sh
          ./build.sh darwin amd64
          ./build.sh dragonfly amd64
          ./build.sh freebsd 386
          ./build.sh freebsd amd64
          ./build.sh linux 386
          ./build.sh linux amd64
          ./build.sh linux arm
          ./build.sh linux arm64
          ./build.sh linux mips
          ./build.sh linux mipsle
          ./build.sh linux mips64
          ./build.sh linux mips64le
          ./build.sh linux ppc64
          ./build.sh linux ppc64le
          ./build.sh linux s390x
          ./build.sh openbsd 386
          ./build.sh openbsd amd64
          ./build.sh windows 386
          ./build.sh windows amd64
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./bin/*
          asset_name: build.zip
          asset_content_type: application/zip
#       - name: Upload artifact
#         uses: actions/upload-artifact@master
#         with:
#           name: build
#           path: bin
